apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: phoebeho14/demo:2.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: TEST
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: test
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: demo-config