apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: phoebeho14/demo:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: demo-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: example
data:
  application.properties: |
    spring.profiles.active=dev
    spring.data.rest.base-path=/api
    spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
    spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
    spring.jpa.hibernate.ddl-auto=none
    mybatis.mapper-locations=classpath:mappers/*.xml
    springdoc.swagger-ui.path=/swagger-ui.html
    spring.datasource.url=jdbc:mysql://mysql:13306/db1?useSSL=false&allowPublicKeyRetrieval=true
    spring.datasource.username=root
    spring.datasource.password=1234
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    jwt.secret=p2s5v8y/B?E(H+MbQeThVmYq3t6w9z$C&F)J@NcRfUjXnZr4u7x!A%D*G-KaPdS
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: example
type: Opaque
data:
  password: MTIzNA==
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: example
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: example
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer