apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: example
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql